- name: Prepare Proxmox for Terraform
  hosts: nodes
  remote_user: root

  tasks:
    - name: Remove Terraform user
      ansible.builtin.shell: pveum user delete terraform@pve
      ignore_errors: true

    - name: Setup Terraform user
      ansible.builtin.shell: pveum user add terraform@pve

    - name: Remove Terraform role
      ansible.builtin.shell: pveum role delete Terraform
      ignore_errors: true

    - name: Setup Terraform role
      ansible.builtin.shell: |
        pveum role add Terraform -privs "
          Datastore.Allocate
          Datastore.AllocateSpace
          Datastore.AllocateTemplate
          Datastore.Audit
          Pool.Allocate
          Sys.Audit
          Sys.Console
          Sys.Modify
          SDN.Use
          VM.Allocate
          VM.Audit
          VM.Clone
          VM.Config.CDROM
          VM.Config.Cloudinit
          VM.Config.CPU
          VM.Config.Disk
          VM.Config.HWType
          VM.Config.Memory
          VM.Config.Network
          VM.Config.Options
          VM.Migrate
          VM.Monitor
          VM.PowerMgmt
          User.Modify"

    - name: Assign role to user
      ansible.builtin.shell: pveum aclmod / -user terraform@pve -role Terraform

    - name: Setup api token
      ansible.builtin.shell: |
        pveum user token add terraform@pve provider --privsep=0 
      register: api_token

    - name: Output api token
      debug:
        var: api_token.stdout_lines
