- name: Setup QEMU Guest agent
  hosts: vms

  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
      become: true

    - name: Start qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
