---
# Backup
backup_dir: "/mnt/backup-nfs/gitlab"
nfs_share: "/mnt/storage/secure/apps/gitlab"

# Core paths (Omnibus GitLab)
gitlab_backup_dir: "/var/opt/gitlab/backups"
gitlab_config_dir: "/etc/gitlab"
gitlab_work_dir: "/var/tmp/gitlab-backup"

# Executables
gitlab_backup_cmd: "gitlab-backup create"     # Omnibus wrapper
bash_path: "/bin/bash"
rclone_path: "/usr/bin/rclone"

# Rclone
rclone_transfers: 4
rclone_checkers: 8

# Retention
local_keep_days: 14
remote_prune_enabled: true
remote_keep_days: 30

# Systemd schedule
systemd_unit_name: "gitlab-backup"
systemd_timer_calendar: "daily"   # e.g. "03:30" or "Mon..Fri 02:15"
systemd_user: "root"
systemd_group: "root"

# Performance/operational toggles
ionice_class: 2         # 1=RT,2=BE,3=Idle
ionice_level: 4         # 0..7 (lower=favor)
nice_level: 10
tmp_umask: "077"

# Safety
fail_if_rclone_missing: true
ensure_dirs_mode: "0750"
script_path: "/usr/local/sbin/gitlab-backup.sh"

