name: 'CI'
on:
  pull_request:

jobs:
  ansible-validate:
    name: Ansible Validate
    runs-on: self-hosted
    environment: homelab
    defaults:
      run:
        working-directory: ./nodes/configuration
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Activate Python VE
        run: source .venv/bin/activate

      - name: Setup PIP
        run: .venv/bin/python3 -m pip install --upgrade pip

      - name: Setup Ansible-lint
        run: .venv/bin/pip install ansible ansible-lint

      - name: Run Ansible-lint
        run: PYTHONTRACEMALLOC=1 .venv/bin/ansible-lint .

  terraform-validate:
    name: Terraform Validate
    runs-on: self-hosted
    environment: homelab
    defaults:
      run:
        working-directory: ./nodes/infrastructure/gryffindor
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=homelab" \
            -backend-config="key=terraform/terraform.tfstate" \
            -backend-config="region=dummy" \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            -backend-config="endpoints={s3=\"${{ secrets.S3_ENDPOINT }}\"}" \
            -backend-config="skip_requesting_account_id=true" \
            -backend-config="skip_credentials_validation=true" \
            -backend-config="skip_metadata_api_check=true" \
            -backend-config="skip_region_validation=true" \
            -backend-config="use_path_style=true"

      - name: terraform check format
        run: terraform fmt -check -diff -recursive

      - name: terraform validate
        run: terraform validate
