name: 'Terraform CI'
on:
  pull_request:

jobs:
  terraform:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./nodes/gryffindor/infrastructure
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up S3 credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}" >> $GITHUB_ENV

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: terraform init
        run: terraform init

      - name: terraform check format
        run: terraform fmt -check

      - name: terraform validate
        run: terraform validate
