---
- name: Ensure working and backup directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ ensure_dirs_mode }}"
  loop:
    - "{{ gitlab_backup_dir }}"

- name: Install rclone if missing
  apt:
    name: rclone
    state: present
    update_cache: true

# Optional: tighten perms on /etc/gitlab (defense-in-depth)
- name: Set permissions on config files
  file:
    path: "{{ item }}"
    mode: "0640"
  loop:
    - "{{ gitlab_config_dir }}/gitlab.rb"
    - "{{ gitlab_config_dir }}/gitlab-secrets.json"
  register: perm_set
  failed_when: false
  changed_when: false

