---
- name: Deploy systemd service
  template:
    src: gitlab-backup.service.j2
    dest: "/etc/systemd/system/{{ systemd_unit_name }}.service"
    mode: "0644"
  notify: [systemd daemon-reload]

- name: Deploy systemd timer
  template:
    src: gitlab-backup.timer.j2
    dest: "/etc/systemd/system/{{ systemd_unit_name }}.timer"
    mode: "0644"
  notify: [systemd daemon-reload]

- name: Enable & start timer
  systemd:
    name: "{{ systemd_unit_name }}.timer"
    enabled: true
    state: started

